setup.py: update to v1.0.0 of certbot_dns_route53
cert_lambda failed to load with error:
AttributeError: 'module' object has no attribute 'TLSSNI01Response'

This issue related to acme version
Updating requirements to certbot-dns-route53 v1.0.0 requirements